export const API_ENDPOINTS = Object.freeze({
  auth: {
    login: "/auth/login",
    adminLogin: "/auth/admin/login",
    register: "/auth/register",
    logout: "/auth/logout",
    me: "/auth/me",
    profile: "/auth/profile",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    adminCredentialRecovery: "/auth/admin/recovery",
  },
  uploads: {
    create: "/uploads",
    fromUrl: "/uploads/from-url",
  },
  csr: {
    applications: "/csr/applications",
    application: (applicationId: string) => `/csr/applications/${encodeURIComponent(applicationId)}`,
  },
  donations: {
    create: "/donations",
    detail: (transactionId: string) => `/donations/${encodeURIComponent(transactionId)}`,
    payment: (transactionId: string) => `/donations/${encodeURIComponent(transactionId)}/payment`,
  },
  serviceOrders: {
    create: "/service-orders",
    detail: (transactionId: string) => `/service-orders/${encodeURIComponent(transactionId)}`,
    payment: (transactionId: string) => `/service-orders/${encodeURIComponent(transactionId)}/payment`,
  },
  consultations: {
    create: "/consultations",
  },
  engagement: {
    contactInquiries: "/contact/inquiries",
    newsletterSubscriptions: "/newsletter/subscriptions",
    supportTickets: "/support/tickets",
  },
  clientDashboard: {
    overview: "/client/dashboard",
  },
  clientInvoices: {
    list: "/client/invoices",
    pay: (invoiceId: string) => `/client/invoices/${encodeURIComponent(invoiceId)}/pay`,
  },
  clientNotifications: {
    list: "/client/notifications",
    readAll: "/client/notifications/read-all",
    read: (notificationId: string) =>
      `/client/notifications/${encodeURIComponent(notificationId)}/read`,
    remove: (notificationId: string) =>
      `/client/notifications/${encodeURIComponent(notificationId)}`,
  },
  clientDonations: {
    list: "/client/donations",
    summary: "/client/donations/summary",
    detail: (id: string) => `/client/donations/${encodeURIComponent(id)}`,
  },
  clientCsrApplications: {
    list: "/client/csr-applications",
    detail: (id: string) => `/client/csr-applications/${encodeURIComponent(id)}`,
  },
  clientInternshipApplications: {
    list: "/client/internship-applications",
    detail: (id: string) => `/client/internship-applications/${encodeURIComponent(id)}`,
  },
  clientStudioOrders: {
    list: "/client/studio-orders",
    summary: "/client/studio-orders/summary",
    detail: (id: string) => `/client/studio-orders/${encodeURIComponent(id)}`,
  },
  clientCertificates: {
    list: "/client/certificates",
    summary: "/client/certificates/summary",
    detail: (id: string) => `/client/certificates/${encodeURIComponent(id)}`,
  },
  clientSupportTickets: {
    list: "/client/support-tickets",
    summary: "/client/support-tickets/summary",
    detail: (id: string) => `/client/support-tickets/${encodeURIComponent(id)}`,
  },
  studioOrders: {
    create: "/studio/orders",
    list: "/studio/orders",
    detail: (orderNumber: string) => `/studio/orders/${encodeURIComponent(orderNumber)}`,
  },
  admin: {
    users: "/admin/users",
    user: (userId: string) => `/admin/users/${encodeURIComponent(userId)}`,
    userStatus: (userId: string) => `/admin/users/${encodeURIComponent(userId)}/status`,
    userRole: (userId: string) => `/admin/users/${encodeURIComponent(userId)}/role`,
    userDependencies: (userId: string) => `/admin/users/${encodeURIComponent(userId)}/dependencies`,
    usersPermissionsAll: "/admin/users/permissions/all",
    services: "/admin/services",
    service: (serviceId: string) => `/admin/services/${encodeURIComponent(serviceId)}`,
    roles: "/admin/roles",
    role: (roleId: string) => `/admin/roles/${encodeURIComponent(roleId)}`,
    rolesSelect: "/admin/roles/select",
    rolesStats: "/admin/roles/stats",
    rolesPermissionsAll: "/admin/roles/permissions/all",
    tanyaMahreen: "/admin/tanya-mahreen",
    tanyaMahreenStats: "/admin/tanya-mahreen/stats",
    tanyaMahreenPackage: (packageId: string) => `/admin/tanya-mahreen/packages/${encodeURIComponent(packageId)}`,
    campaigns: "/admin/peduli-mahreen/campaigns",
    campaign: (campaignId: string) => `/admin/peduli-mahreen/campaigns/${encodeURIComponent(campaignId)}`,
    campaignStats: "/admin/peduli-mahreen/stats",
    csrOverview: "/admin/csr/overview",
    studioInventory: "/admin/studio/inventory",
    studioProducts: "/admin/studio/products",
    studioProduct: (productId: string) => `/admin/studio/products/${encodeURIComponent(productId)}`,
    internshipAnalytics: "/admin/internship/analytics",
    commandCenter: "/admin/operations/command-center",
    verificationOverview: "/admin/verification/overview",
    verificationRequest: (requestId: string) => `/admin/verification/requests/${encodeURIComponent(requestId)}`,
    verificationCertificates: "/admin/verification/certificates",
    verificationCertificate: (certificateId: string) =>
      `/admin/verification/certificates/${encodeURIComponent(certificateId)}`,
    verificationCertificateRevoke: (certificateId: string) =>
      `/admin/verification/certificates/${encodeURIComponent(certificateId)}/revoke`,
    studioPortfolios: "/admin/studio/portfolios",
    studioPortfolio: (portfolioId: string) =>
      `/admin/studio/portfolios/${encodeURIComponent(portfolioId)}`,
    events: "/admin/newsroom/events",
    event: (eventId: string) => `/admin/newsroom/events/${encodeURIComponent(eventId)}`,
    eventStatus: (eventId: string) => `/admin/newsroom/events/${encodeURIComponent(eventId)}/status`,
    eventStats: "/admin/newsroom/events/stats",
    eventRegistrations: (eventId: string) => `/admin/newsroom/events/${encodeURIComponent(eventId)}/registrations`,
    webinars: "/admin/newsroom/webinars",
    webinar: (webinarId: string) => `/admin/newsroom/webinars/${encodeURIComponent(webinarId)}`,
    webinarStatus: (webinarId: string) => `/admin/newsroom/webinars/${encodeURIComponent(webinarId)}/status`,
    webinarStats: "/admin/newsroom/webinars/stats",
    tags: "/admin/newsroom/topics",
    tag: (tagId: string) => `/admin/newsroom/topics/${encodeURIComponent(tagId)}`,
    auditLogs: "/admin/overview/audit-logs",
    portfolios: "/admin/portfolios",
    analyticsOverview: "/admin/analytics/overview",
    analyticsTraffic: "/admin/analytics/traffic",
    analyticsTopPages: "/admin/analytics/top-pages",
    analyticsDevices: "/admin/analytics/devices",
    analyticsFunnel: "/admin/analytics/funnel",
    analyticsEcosystem: "/admin/analytics/ecosystem",
    analyticsContentPerformance: "/admin/analytics/content-performance",
    reportsLogs: "/admin/reports/logs",
    reportsExport: "/admin/reports/export",
    clients: "/admin/clients",
    client: (clientId: string) => `/admin/clients/${encodeURIComponent(clientId)}`,
    clientStats: (clientId: string) => `/admin/clients/${encodeURIComponent(clientId)}/stats`,
    clientActivity: (clientId: string) => `/admin/clients/${encodeURIComponent(clientId)}/activity`,
    clientOrders: (clientId: string) => `/admin/clients/${encodeURIComponent(clientId)}/orders`,
    clientCertificates: (clientId: string) => `/admin/clients/${encodeURIComponent(clientId)}/certificates`,
    clientConsultations: (clientId: string) => `/admin/clients/${encodeURIComponent(clientId)}/consultations`,
    contactInquiries: "/admin/contact-inquiries",
    contactInquiry: (id: string) => `/admin/contact-inquiries/${encodeURIComponent(id)}`,
    contactInquiryStatus: (id: string) => `/admin/contact-inquiries/${encodeURIComponent(id)}/status`,
    supportTickets: "/admin/support-tickets",
    supportTicket: (id: string) => `/admin/support-tickets/${encodeURIComponent(id)}`,
    supportTicketStatus: (id: string) => `/admin/support-tickets/${encodeURIComponent(id)}/status`,
  },
  internships: {
    create: "/internships/applications",
  },
  webinars: {
    register: (slug: string) => `/webinars/${encodeURIComponent(slug)}/registrations`,
    payment: (slug: string) => `/webinars/${encodeURIComponent(slug)}/payments`,
  },
  newsroom: {
    database: "/newsroom",
    articles: "/newsroom/articles",
    article: (slug: string) => `/newsroom/articles/${encodeURIComponent(slug)}`,
    articleView: (slug: string) => `/newsroom/articles/${encodeURIComponent(slug)}/view`,
    articleComments: (slug: string) => `/newsroom/articles/${encodeURIComponent(slug)}/comments`,
  },
  studioPublic: {
    products: "/products",
    product: (slug: string) => `/products/${encodeURIComponent(slug)}`,
    collections: "/collections",
    specializations: "/collections/specializations",
  },
  events: {
    list: "/events",
    event: (eventId: string) => `/events/${encodeURIComponent(eventId)}`,
    register: (eventId: string) => `/events/${encodeURIComponent(eventId)}/registrations`,
    registration: (eventId: string, registrationId: string) =>
      `/events/${encodeURIComponent(eventId)}/registrations/${encodeURIComponent(registrationId)}`,
    payment: (eventId: string) => `/events/${encodeURIComponent(eventId)}/payments`,
    paymentCallback: "/events/payments/callback",
    eventStream: "/newsroom/events/stream",
  },
  analytics: {
    track: "/analytics/track",
  },
  verification: {
    check: "/verification/check",
  },
  faqs: {
    list: "/faqs",
  },
});
